const ROW_HEIGHT = 37;
const HEADER_HEIGHT = 37;
const FOOTER_HEIGHT = 37;
const SCROLLBAR_WIDTH = 17;
const ESTIMATED_NUM_ROWS = 10;

export { ESTIMATED_NUM_ROWS, FOOTER_HEIGHT, HEADER_HEIGHT, ROW_HEIGHT, SCROLLBAR_WIDTH };
