const DEFAULT_ROW_HEIGHT = 37;
const DEFAULT_HEADER_HEIGHT = 37;
const DEFAULT_FOOTER_HEIGHT = 37;
const DEFAULT_SCROLLBAR_WIDTH = 17;
const ESTIMATED_NUM_ROWS = 10;

export {
  DEFAULT_FOOTER_HEIGHT,
  DEFAULT_HEADER_HEIGHT,
  DEFAULT_ROW_HEIGHT,
  DEFAULT_SCROLLBAR_WIDTH,
  ESTIMATED_NUM_ROWS
};
